<?php

declare(strict_types=1);

namespace Podoko\ElasticsearchTest\Tests\Functional\Factory;

use Podoko\ElasticsearchTest\Tests\Functional\Model\Post;
use Zenstruck\Foundry\ObjectFactory;

/**
 * Foundry factory for the Post DTO.
 *
 * Used in ObjectFactory mode (no Doctrine persistence): instances created are plain PHP
 * objects, later indexed into Elasticsearch via PostIndexer.
 *
 * @extends ObjectFactory<Post>
 */
final class PostFactory extends ObjectFactory
{
    public static function class(): string
    {
        return Post::class;
    }

    /**
     * Default values generated by Faker.
     * Tests can override any field via createOne(['status' => 'draft']).
     */
    protected function defaults(): array
    {
        return [
            'id'     => self::faker()->uuid(),
            'title'  => self::faker()->sentence(4),
            'status' => self::faker()->randomElement(['published', 'draft']),
            'body'   => self::faker()->paragraph(),
        ];
    }
}
